### ISSUE TITLE
is it suitable for tds754d?

### ISSUE THREAD

**Issue by youxiaojie** [scbrac/pyTDSserial#1]
is it suitable for tds754d?

**Comment by scbrac** [comment]
I have no experience with TDS754D as i don't have access to that model, I'm afraid. But if it's got a serial interface, changes are good, pyTDSserial works. I know it works for TDS 200 series.

**Comment by youxiaojie** [comment]
dear friend, how can i determine where my serial pot works? I use putty connect serial port. is there some command to test my connexion and the port? I see the manual, and it said serial port is for printer. what type of tektronix did you test except 200 series? how about tds 380? thanks.

**Comment by scbrac** [comment]
Hi,

excuse me for answering so late but your e-mail was sorted out as spam.

A typical command to check your connection is to query the ID of your oscilloscope. You do this by sending "*IDN?" to the scope, it should answer with its ID.

In my experience it's best to select 9600 Baud as transfer rate, it's the only one I could get to work.

Right now I have no access to the information of other Textronix series I tried successfully. I might send you the information next week
